---

services:
  gosa-www:
    build:
      context: container/www
    volumes:
      - type: bind
        source: /PATH/TO/GOSA2
        target: /srv/gosa/gosa/
    depends_on:
      gosa-ldap:
        condition: service_started
      gosa-ldap2:
        condition: service_started
    networks:
      gosa:
        aliases:
          - gosa.gosa.example.com
    ports:
      - 80:80
    expose:
      - 80
      - 443
    hostname: gosa.gosa.example.com
    environment:
      LDAP_LIST: "ldap://ldap.gosa.example.com ldap://ldap2.gosa.example.com"
      ROOT_DN: ""
      ROOT_PW: ""
      USE_TLS: true
      GSA_UID: "gsa"
      GSA_PW: "tester"
  gosa-ldap:
    build:
      context: container/ldap
      args:
        HEALTHCHECK_LDAP_USER_DN: "cn=manager,dc=example,dc=com"
        HEALTHCHECK_LDAP_USER_PASSWORD: "secret"
        HEALTHCHECK_LDAP_BASE: "dc=example,dc=com"
        HEALTHCHECK_LDAP_URI: "ldap://ldap.gosa.example.com"
    networks:
      gosa:
        aliases:
          - ldap.gosa.example.com
    ports:
      - "127.0.0.1:3389:389"
      - "127.0.0.1:6636:636"
    expose:
      - "389"
      - "636"
    hostname: ldap.gosa.example.com
    volumes:
      - gosa-ldap-db:/var/lib/ldap
      - type: bind
        source: /PATH/TO/CERTS
        target: /certs/
  gosa-ldap2:
    build:
      context: container/ldap
      args:
        HEALTHCHECK_LDAP_USER_DN: "cn=manager,dc=example,dc=com"
        HEALTHCHECK_LDAP_USER_PASSWORD: "secret"
        HEALTHCHECK_LDAP_BASE: "dc=example,dc=com"
        HEALTHCHECK_LDAP_URI: "ldap://ldap2.gosa.example.com"
    networks:
      gosa:
        aliases:
          - ldap2.gosa.example.com
    ports:
      - "127.0.0.1:3899:389"
      - "127.0.0.1:6366:636"
    expose:
      - "389"
      - "636"
    hostname: ldap2.gosa.example.com
    volumes:
      - gosa-ldap2-db:/var/lib/ldap
      - type: bind
        source: /PATH/TO/CERTS
        target: /certs/
    depends_on:
      gosa-ldap:
        condition: service_started

volumes:
  gosa-ldap-db: {}
  gosa-ldap2-db: {}

networks:
  gosa:
