apiVersion: v1
kind: Service
metadata:
  name: gosa-openldap
  namespace: gosa
  labels:
    app: gosa-openldap
spec:
  type: ClusterIP
  ports:
  - port: 389
    name: ldap
  - port: 636
    name: ldaps
  clusterIP: None
  selector:
    app: gosa-openldap

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gosa-openldap
  namespace: gosa
spec:
  serviceName: gosa-openldap
  selector:
    matchLabels:
      app: gosa-openldap
  replicas: 2
  template:
    metadata:
      labels:
        app: gosa-openldap
    spec:
      subdomain: gosa-openldap
      dnsConfig:
        searches:
          - gosa-openldap.gosa.svc.cluster.local
      containers:
        - name: gosa-openldap
          image: bitnami/openldap:2.6
          volumeMounts:
            - name: ldapdata
              mountPath: /bitnami/openldap
          ports:
            - containerPort: 389
              name: ldap
            - containerPort: 636
              name: ldaps
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: LDAP_PORT_NUMBER
              value: "389"
            - name: LDAP_LDAPS_PORT_NUMBER
              value: "636"
            - name: LDAP_SKIP_DEFAULT_TREE
              value: "no"
            - name: LDAP_ENABLE_TLS
              value: "no"
            - name: LDAP_ENABLE_SYNCPROV
              value: "yes"
  volumeClaimTemplates:
    - metadata:
        name: ldapdata
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 3Gi
