apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldap-0
  namespace: gosa
spec:
  storageClassName: csi-rbd-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldap-1
  namespace: gosa
spec:
  storageClassName: csi-rbd-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi